name: Deploy To Server

run-name: Deploy To Server -- ${{inputs.tag || github.ref_name}}

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: Tag
        required: false
        options:
          - 1.0.0

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Configure Files
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Connect To Server
        run: |
          ssh -i id_rsa ${{secrets.AWS_HOST}}@${{secrets.AWS_HOST_IP}}
          sudo docker --version
          sudo docker ps -a
          whoami
          su -u ${{secrets.AWS_HOST}}
          whoami
          ls
