name: Deploy To Server

run-name: Deploy To Server -- ${{inputs.tag}}

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        type: choice
        description: Tag
        required: false
        options:
          - 1.0.0

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Connect to Server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh -i id_rsa ec2-user@54.226.103.0
          sudo docker --version
          sudo docker ps