name: Send Discord Notifications

run-name: Send Discord Notification -- ${{github.event.pull_request.user}} -- ${{github.ref_name}}

on:
  pull_request:


jobs:
  notify-discord:
    runs-on: ubuntu-24.04
    steps:
      - name: Get Current Time
        id: current_time
        uses: josStorer/get-current-time@v2.3.1 # Or another similar action
        with:
          format: 'YYYY-MM-DD-HH-mm-ss' # Customize the format as needed

      - name: Send Discord Message
        uses: Ilshidur/action-discord@master
        with:
          args: | 
            "A new PR from ${{github.event.pull_request.user}} please review"
            ""
            ```"PR Title -- ${{github.event.pull_request.title}}"
            "PR Base Branch -- ${{github.event.pull_request.head.ref}}"
            "PR Target Branch -- ${{github.event.pull_request.base.ref}}"
            "PR Time Stamp -- ${{steps.current_time.outputs.formattedTime}}"```
            ""
            "[PR Link](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})"
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK_URL}}
